name: sekolah_app
description: Aplikasi Manajemen Sekolah - SaaS Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network
  dio: ^5.7.0

  # Storage
  flutter_secure_storage: ^9.2.4

  # Routing
  go_router: ^14.8.1

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2

  # Utils
  equatable: ^2.0.7
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  json_annotation: ^4.9.0
  webview_flutter: ^4.13.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/rive/
